# Generated by Django 4.2.13 on 2024-05-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdfs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="pdfs/static")),
            ],
        ),
        migrations.RemoveField(
            model_name="pdfupload",
            name="file",
        ),
        migrations.AddField(
            model_name="pdfupload",
            name="files",
            field=models.ManyToManyField(to="pdfs.file"),
        ),
    ]
