# Generated by Django 4.2.13 on 2024-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdfs", "0002_file_remove_pdfupload_file_pdfupload_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("files", models.FileField(upload_to="media/")),
            ],
        ),
        migrations.RemoveField(
            model_name="pdfupload",
            name="files",
        ),
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="PDFUpload",
        ),
    ]
